# Lab-01-1 Tensor Manipulation Code Seminar

First Author: Seungjae Ryan Lee (seungjaeryanlee at gmail dot com)
Second Author: Ki Hyun Kim (nlp.with.deep.learning at gmail dot com)
Seminar Instructor: Taewon Kang (itschool@itsc.kr)

<div class="alert alert-warning">
    NOTE: This corresponds to <a href="https://www.youtube.com/watch?v=ZYX0FaqUeN4&t=23s&list=PLlMkM4tgfjnLSOjrEJN31gZATbcj_MpUm&index=25">Lab 8 of Deep Learning Zero to All Season 1 for TensorFlow</a>.
</div>

## Imports

`pip install -r requirements.txt` 을 실행해서 패키지를 설치하십시오.

In [1]:
import numpy as np
import torch

## NumPy 리뷰

`numpy` 라이브러리를 활용하여 간단한 선형대수 Code를 제작해 봅시다.

### 1차원 행렬

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t) # t라는 이름을 가진 1차원 행렬을 제작하여, 출력한다.

[ 0.  1.  2.  3.  4.  5.  6.]


In [3]:
print('Rank  of t: ', t.ndim) # 1차원 행렬의 rank와 shape에 대해 알아본다.
print('Shape of t: ', t.shape)

Rank  of t:  1
Shape of t:  (7,)


In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # 행렬에 접근하는 방법
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])   # 슬라이싱으로 행렬에 접근하는 방법
print('t[:2] t[3:]     = ', t[:2], t[3:])      # 슬라이싱으로 행렬에 접근하는 방법

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [ 2.  3.  4.] [ 4.  5.]
t[:2] t[3:]     =  [ 0.  1.] [ 3.  4.  5.  6.]


### 2차원 행렬

In [5]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t) # t라는 이름을 가진 2차원 행렬을 제작하여, 출력한다.

[[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]
 [ 10.  11.  12.]]


In [6]:
print('Rank  of t: ', t.ndim) # 2차원 행렬의 rank와 shape에 대해 알아본다.
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


## PyTorch 사용 (Numpy보다 더 간편하게 표현 가능)

### PyTorch를 활용한 1차원 행렬 구현

In [7]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t) # PyTorch에서는, FloatTensor 함수를 활용해서 행렬을 제작할 수 있다. 
# 정수만 표현 가능한 intTensor 함수도 있지만, 딥러닝 환경에서는 거의 쓸 일이 없을 것이다.

tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
print(t.dim())  # 행렬 t의 dimension
print(t.shape)  # 행렬 t의 shape
print(t.size()) # size() 함수를 사용해서 shape 구하기
print(t[0], t[1], t[-1])  # 행렬 각 요소의 접근
print(t[2:5], t[4:-1])    # 슬라이싱으로 행렬에 접근하는 방법
print(t[:2], t[3:])       # 슬라이싱으로 행렬에 접근하는 방법

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### PyTorch를 활용한 2차원 행렬 구현

In [9]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim())  # 행렬 t의 dimension
print(t.size()) # 행렬 t의 shape
print(t[:, 1]) # 행렬 t의 1행 표현, Array는 0부터 시작하므로 1행은 2, 5, 8, 11 이 된다.
print(t[:, 1].size()) # 요소가 4개 있으므로 Size는 4가 출력된다.
print(t[:, :-1]) # -1을 사용했으므로, 전체 2행에서 0~1행만 출력된다. (Python의 특징)

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Shape, Rank, Axis

In [11]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                       ]])

In [12]:
print(t.dim())  # 행렬 rank  = 4
print(t.size()) # 행렬 shape = (1, 2, 3, 4)

4
torch.Size([1, 2, 3, 4])


## PyTorch에서 자주 사용되는 Operation

### Mul vs. Matmul

In [13]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

# [ 1 2 ] * [1 2] = [5, 11] 
# [ 3 4 ]

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2)) # 같은 위치에 있는 원소끼리 곱셈 연산을 수행


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### 브로드캐스팅

<div class="alert alert-warning">
    Carelessly using broadcasting can lead to code hard to debug.
</div>

In [14]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [15]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [16]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### 평균(Mean)

In [17]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [18]:
# Can't use mean() on integers --> mean() 함수는 float 타입만 계산 가능
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


You can also use `t.mean` for higher rank tensors to get mean of all elements, or mean by particular dimension.

In [19]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [20]:
print(t.mean()) # 행렬 평균 계산, 행,열 별로 나눠서 계산해 줄 수 있음
print(t.mean(dim=0)) # (1+3)/2, (2+4)/2
print(t.mean(dim=1)) # (1+2)/2, (3+4)/2
print(t.mean(dim=-1)) # 동일

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### 행렬 덧셈(Sum)

In [21]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [22]:
print(t.sum())
print(t.sum(dim=0)) #1+3, 2+4
print(t.sum(dim=1)) #1+2, 3+4
print(t.sum(dim=-1)) #1+2, 3+4

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max 와 Argmax

In [23]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


The `max` operator returns one value if it is called without an argument.

In [24]:
print(t.max()) # 가장 높은 하나의 value 반환 ($)

tensor(4.)


The `max` operator returns 2 values when called with dimension specified. The first value is the maximum value, and the second value is the argmax: the index of the element with maximum value.

In [25]:
print(t.max(dim=0)) # 가장 높은 수를 가진 dimension의 value와 위치를 알려줌
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

(tensor([3., 4.]), tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [26]:
print(t.max(dim=1))
print(t.max(dim=-1))

(tensor([2., 4.]), tensor([1, 1]))
(tensor([2., 4.]), tensor([1, 1]))


### View

<div class="alert alert-warning">
    배우기 어렵지만, 한번 익혀두면 유용합니다!
</div>

In [27]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape) # 2*3 행렬 size 정보 제공

torch.Size([2, 2, 3])


In [28]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [29]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze

In [30]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft) # 행렬 출력
print(ft.shape) #3*1 행렬

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [31]:
print(ft.squeeze()) # 행렬 뒤집기 (전치행렬)
print(ft.squeeze().shape) # shape 출력

tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze

In [32]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [33]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [34]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [35]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape) # 행렬 뒤집기

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [36]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Scatter (for one-hot encoding)

<div class="alert alert-warning">
    Scatter is a very flexible function. We only discuss how to use it to get a one-hot encoding of indices.
</div>

In [37]:
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt) # Chart처럼, value를 지정해 줌

tensor([[0],
        [1],
        [2],
        [0]])


In [38]:
one_hot = torch.zeros(4, 3) # 4개의 data, 3개의 class (0, 1, 2)
one_hot.scatter_(1, lt, 1)
print(one_hot) 
# 0
# 0 1
# 0 1 2
# 0

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


### Casting

In [39]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [40]:
print(lt.float()) # 자료형 변환

tensor([1., 2., 3., 4.])


In [41]:
bt = torch.ByteTensor([True, False, False, True])
print(bt) # ByteTensor 자료형(True, False) --> 일종의 bool

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [42]:
print(bt.long()) # ByteTensor 자료형을 Long이나, Float로 변환
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenation

In [43]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [44]:
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1)) # 두 행렬을 서로 Concate 함.

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

In [45]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [46]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1)) # 서로 다른 행렬을 결합 (Stacking) 함.

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [47]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros Like

In [48]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [49]:
print(torch.ones_like(x)) # 특정한 값의 텐서 생성: 사이즈를 튜플로 입력하지 않고, 기존의 텐서로 정의
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [50]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [51]:
print(x.mul(2.)) # 곱한 결과 출력 --> 저장되지는 않음
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


## Miscellaneous

### Zip

In [52]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [53]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
